import { Application } from '../types/application';

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "1",
    startupName: "EcoTech Solutions",
    founderName: "Sarah Chen",
    founderEmail: "sarah@ecotech.com",
    industry: "CleanTech",
    stage: "Seed",
    location: "San Francisco, CA",
    requestedFunding: 500000,
    aiScore: 92,
    marketScore: 95,
    teamScore: 88,
    ideaScore: 94,
    fitScore: 91,
    submittedAt: "2024-01-15T10:30:00Z",
    status: "review-pending",
    description: "Developing AI-powered solar panel optimization systems for residential and commercial use.",
    teamSize: 4,
    previousFunding: 50000,
    revenueStage: "Pre-revenue",
  },
  {
    id: "2",
    startupName: "HealthAI",
    founderName: "Dr. Michael Rodriguez",
    founderEmail: "michael@healthai.com",
    industry: "HealthTech",
    stage: "Pre-Seed",
    location: "Boston, MA",
    requestedFunding: 250000,
    aiScore: 87,
    marketScore: 90,
    teamScore: 85,
    ideaScore: 88,
    fitScore: 85,
    submittedAt: "2024-01-14T14:20:00Z",
    status: "interview-scheduled",
    description: "AI-powered diagnostic tool for early detection of cardiovascular diseases using ECG pattern analysis.",
    teamSize: 3,
    previousFunding: 0,
    revenueStage: "Pre-revenue",
    interviewDate: "2024-01-22T15:00:00Z",
  },
  {
    id: "3",
    startupName: "AgriBot",
    founderName: "James Kim",
    founderEmail: "james@agribot.com",
    industry: "AgTech",
    stage: "Seed",
    location: "Austin, TX",
    requestedFunding: 750000,
    aiScore: 84,
    marketScore: 82,
    teamScore: 87,
    ideaScore: 85,
    fitScore: 83,
    submittedAt: "2024-01-13T09:15:00Z",
    status: "interview-completed",
    description: "Autonomous farming robots for precision agriculture and crop monitoring using computer vision and IoT sensors.",
    teamSize: 6,
    previousFunding: 100000,
    revenueStage: "Early revenue",
    interviewDate: "2024-01-18T10:00:00Z",
    interviewNotes: "Strong technical team, proven pilot customers, but high capital requirements for scaling.",
  },
  {
    id: "4",
    startupName: "DataFlow Analytics",
    founderName: "Alex Thompson",
    founderEmail: "alex@dataflow.com",
    industry: "Data Analytics",
    stage: "Seed",
    location: "Seattle, WA",
    requestedFunding: 600000,
    aiScore: 89,
    marketScore: 91,
    teamScore: 92,
    ideaScore: 87,
    fitScore: 88,
    submittedAt: "2024-01-11T11:30:00Z",
    status: "accepted",
    description: "Real-time data pipeline and analytics platform for enterprise customers with ML-powered insights.",
    teamSize: 8,
    previousFunding: 200000,
    revenueStage: "Growing revenue",
  },
  {
    id: "5",
    startupName: "CloudSync Analytics",
    founderName: "Ryan Foster",
    founderEmail: "ryan@cloudsync.com",
    industry: "SaaS & Cloud Computing",
    stage: "Seed",
    location: "San Diego, CA",
    requestedFunding: 450000,
    aiScore: 88,
    marketScore: 90,
    teamScore: 86,
    ideaScore: 87,
    fitScore: 89,
    submittedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: "agreement-in-progress",
    description: "Enterprise-grade cloud data analytics platform that provides real-time insights across multi-cloud environments.",
    teamSize: 14,
    previousFunding: 350000,
    revenueStage: "$400K ARR",
    agreementTerms: {
      version: 2,
      tenure: "12 months",
      equity: "2.5%",
      equityPercentage: 2.5,
      deliverables: "Weekly mentorship sessions, network access, strategic guidance",
      status: "counter-proposed",
    }
  },
];